// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tester.Integration.EFCore6.Single_context_many_files
{
    // BlahBlahLink
    public class BlahBlahLink
    {
        public int BlahId { get; set; } // BlahID (Primary key)
        public int BlahId2 { get; set; } // BlahID2 (Primary key)

        // Foreign keys

        /// <summary>
        /// Parent Blah pointed by [BlahBlahLink].([BlahId]) (FK_BlahBlahLink_Blah)
        /// </summary>
        public virtual Blah Blah_BlahId { get; set; } // FK_BlahBlahLink_Blah

        /// <summary>
        /// Parent Blah pointed by [BlahBlahLink].([BlahId2]) (FK_BlahBlahLink_Blah2)
        /// </summary>
        public virtual Blah Blah_BlahId2 { get; set; } // FK_BlahBlahLink_Blah2
    }

}
// </auto-generated>
