// <auto-generated>

namespace Tester.Integration.EFCore6.Single_context_many_files
{
    public enum CarOptions
    {
        SunRoof = 0x01,
        Spoiler = 0x02,
        FogLights = 0x04,
        TintedWindows = 0x08,
    }

}
// </auto-generated>
