// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tester.Integration.EFCore6.Single_context_many_files
{
    // CarToColour
    public class CarToColour
    {
        public int CarId { get; set; } // CarId (Primary key)
        public int ColourId { get; set; } // ColourId (Primary key)

        // Foreign keys

        /// <summary>
        /// Parent Car pointed by [CarToColour].([CarId]) (CarToColour_CarId)
        /// </summary>
        public virtual Car Car { get; set; } // CarToColour_CarId

        /// <summary>
        /// Parent Colour pointed by [CarToColour].([ColourId]) (CarToColour_ColourId)
        /// </summary>
        public virtual Colour Colour { get; set; } // CarToColour_ColourId
    }

}
// </auto-generated>
