// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tester.Integration.EFCore6.Single_context_many_files
{
    // TableWithSpaceInColumnOnly
    public class TableWithSpaceInColumnOnly
    {
        public int IdValue { get; set; } // id value (Primary key)
    }

}
// </auto-generated>
