// <auto-generated>
#nullable enable

using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Design;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data;
using System.Data.SqlTypes;
using System.Linq;
using System.Linq.Expressions;
using System.Threading;
using System.Threading.Tasks;

namespace Efrpg.V9SpacedTvfDa
{
    #region Database context interface

    public interface IEfrpgTestDbContext : IDisposable
    {

        int SaveChanges();
        int SaveChanges(bool acceptAllChangesOnSuccess);
        Task<int> SaveChangesAsync(CancellationToken cancellationToken = default(CancellationToken));
        Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken = default(CancellationToken));
        DatabaseFacade Database { get; }
        DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string? ToString();

        EntityEntry Add(object entity);
        EntityEntry<TEntity> Add<TEntity>(TEntity entity) where TEntity : class;
        Task AddRangeAsync(params object[] entities);
        Task AddRangeAsync(IEnumerable<object> entities, CancellationToken cancellationToken = default);
        ValueTask<EntityEntry<TEntity>> AddAsync<TEntity>(TEntity entity, CancellationToken cancellationToken = default) where TEntity : class;
        ValueTask<EntityEntry> AddAsync(object entity, CancellationToken cancellationToken = default);
        void AddRange(IEnumerable<object> entities);
        void AddRange(params object[] entities);

        EntityEntry Attach(object entity);
        EntityEntry<TEntity> Attach<TEntity>(TEntity entity) where TEntity : class;
        void AttachRange(IEnumerable<object> entities);
        void AttachRange(params object[] entities);

        EntityEntry Entry(object entity);
        EntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;

        TEntity? Find<TEntity>(params object?[]? keyValues) where TEntity : class;
        ValueTask<TEntity?> FindAsync<TEntity>(object?[]? keyValues, CancellationToken cancellationToken) where TEntity : class;
        ValueTask<TEntity?> FindAsync<TEntity>(params object?[]? keyValues) where TEntity : class;
        ValueTask<object?> FindAsync(Type entityType, object?[]? keyValues, CancellationToken cancellationToken);
        ValueTask<object?> FindAsync(Type entityType, params object?[]? keyValues);
        object? Find(Type entityType, params object?[]? keyValues);

        EntityEntry Remove(object entity);
        EntityEntry<TEntity> Remove<TEntity>(TEntity entity) where TEntity : class;
        void RemoveRange(IEnumerable<object> entities);
        void RemoveRange(params object[] entities);

        EntityEntry Update(object entity);
        EntityEntry<TEntity> Update<TEntity>(TEntity entity) where TEntity : class;
        void UpdateRange(IEnumerable<object> entities);
        void UpdateRange(params object[] entities);

        IQueryable<TResult> FromExpression<TResult> (Expression<Func<IQueryable<TResult>>> expression);

        // Table Valued Functions
        IQueryable<SpacedColumnTvfReturnModel> SpacedColumnTvf(int? id); // dbo.SpacedColumnTvf
    }

    #endregion

    #region Database context

    public class EfrpgTestDbContext : DbContext, IEfrpgTestDbContext
    {
        public EfrpgTestDbContext()
        {
        }

        public EfrpgTestDbContext(DbContextOptions<EfrpgTestDbContext> options)
            : base(options)
        {
        }


        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer(@"Data Source=(local);Initial Catalog=EfrpgTest;Integrated Security=True;Encrypt=false;TrustServerCertificate=true;Application Name=Generator");
                optionsBuilder.UseLazyLoadingProxies();
            }
        }

        public bool IsSqlParameterNull(SqlParameter param)
        {
            var sqlValue = param.SqlValue;
            var nullableValue = sqlValue as INullable;
            if (nullableValue != null)
                return nullableValue.IsNull;
            return (sqlValue == null || sqlValue == DBNull.Value);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            // Table Valued Functions
            modelBuilder.Entity<SpacedColumnTvfReturnModel>().HasNoKey();
        }


        // Table Valued Functions

        // dbo.SpacedColumnTvf
        public IQueryable<SpacedColumnTvfReturnModel> SpacedColumnTvf(int? id = null)
        {
            return Set<SpacedColumnTvfReturnModel>()
                .FromSqlRaw("SELECT * FROM [dbo].[SpacedColumnTvf]({0})", id)
                .AsNoTracking();
        }
    }

    #endregion

    #region Database context factory

    public class EfrpgTestDbContextFactory : IDesignTimeDbContextFactory<EfrpgTestDbContext>
    {
        private readonly DbContextOptions<EfrpgTestDbContext>? Options;

        public EfrpgTestDbContextFactory()
        {
            Options = null;
        }

        public EfrpgTestDbContextFactory(DbContextOptions<EfrpgTestDbContext> options)
        {
            Options = options;
        }

        public EfrpgTestDbContext CreateDbContext(string[] args)
        {
            return new EfrpgTestDbContext();
        }

        public EfrpgTestDbContext CreateDbContext()
        {
            return Options != null ? new EfrpgTestDbContext(Options) : new EfrpgTestDbContext();
        }

        public EfrpgTestDbContext CreateDbContext(DbContextOptions<EfrpgTestDbContext> options)
        {
            return options == null
                ? new EfrpgTestDbContext()
                : new EfrpgTestDbContext(options);
        }
    }

    #endregion

    #region Stored procedure return models

    public class SpacedColumnTvfReturnModel
    {
        public int? Id { get; set; }
        [Column("My Column")]
        public string MyColumn { get; set; } = null!;
        [Column("Is Active")]
        public bool? IsActive { get; set; }
    }


    #endregion

}
// </auto-generated>
