// <auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using System.Text.Json.Serialization;
using Tester.Integration.EFCore8.Single_context_many_files.Configuration;
using Tester.Integration.EFCore8.Single_context_many_files.Entities;
using Tester.Integration.EFCore8.Single_context_many_files.Interfaces;

namespace Tester.Integration.EFCore8.Single_context_many_files.Contexts
{
    public class EfCoreDbContextFactory : IDesignTimeDbContextFactory<EfCoreDbContext>
    {
        private readonly DbContextOptions<EfCoreDbContext>? Options;

        public EfCoreDbContextFactory()
        {
            Options = null;
        }

        public EfCoreDbContextFactory(DbContextOptions<EfCoreDbContext> options)
        {
            Options = options;
        }

        public EfCoreDbContext CreateDbContext(string[] args)
        {
            return new EfCoreDbContext();
        }

        public EfCoreDbContext CreateDbContext()
        {
            return Options != null ? new EfCoreDbContext(Options) : new EfCoreDbContext();
        }

        public EfCoreDbContext CreateDbContext(DbContextOptions<EfCoreDbContext> options)
        {
            return options == null
                ? new EfCoreDbContext()
                : new EfCoreDbContext(options);
        }
    }
}
// </auto-generated>
