// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Tester.Integration.EfCore3
{
    // Blah
    public class BlahConfiguration : IEntityTypeConfiguration<Blah>
    {
        public void Configure(EntityTypeBuilder<Blah> builder)
        {
            builder.ToTable("Blah", "dbo");
            builder.HasKey(x => x.BlahId).HasName("PK_Blah").IsClustered();

            builder.Property(x => x.BlahId).HasColumnName(@"BlahID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
        }
    }

}
// </auto-generated>
