// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.co.uk/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Registered to: Simon Hughes
// Company      : Reverse POCO
// Licence Type : Commercial
// Licences     : 1
// Valid until  : 15 DEC 2022
//
// The following connection settings were used to generate this file:
//     Connection String Name: "FredDbContext"
//     Connection String:      "Data Source=(local);Initial Catalog=Fred;Integrated Security=True"
//
// Database Edition       : Developer Edition (64-bit)
// Database Engine Edition: Enterprise
// Database Version       : 14.0.2037.2
//
// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace V3Fred
{
    // ScreamAndShout
    public class Kate_ScreamAndShoutConfiguration : IEntityTypeConfiguration<Kate_ScreamAndShout>
    {
        public void Configure(EntityTypeBuilder<Kate_ScreamAndShout> builder)
        {
            builder.ToTable("ScreamAndShout", "Kate");
            builder.HasKey(x => x.KateId).HasName("PK__ScreamAn__8540EE1FFC54DDC8").IsClustered();

            builder.Property(x => x.KateId).HasColumnName(@"KateID").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Description).HasColumnName(@"description").HasColumnType("varchar(20)").IsRequired().IsUnicode(false).HasMaxLength(20);

            // Foreign keys
            builder.HasOne(a => a.ScreamAndShout).WithOne(b => b.Kate_ScreamAndShout).HasForeignKey<Kate_ScreamAndShout>(c => c.KateId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("KateFK");
        }
    }

}
// </auto-generated>
