// <auto-generated>
// ReSharper disable All

using System.CodeDom.Compiler;

namespace Tester.Integration.EFCore6
{
    #region Enumerations

    [GeneratedCode("EF.Reverse.POCO.Generator", "v3.6.0")]
    public enum Car
    {
        Ford = 1,
        Saab = 2,
    }

    [GeneratedCode("EF.Reverse.POCO.Generator", "v3.6.0")]
    public enum Colour
    {
        Red = 1,
        Green = 2,
        Blue = 3,
    }

    [GeneratedCode("EF.Reverse.POCO.Generator", "v3.6.0")]
    public enum DaysOfWeek
    {
        Sun = 0,
        Mon = 1,
        Tue = 2,
        Wed = 3,
        Thu = 4,
        Fri = 6,
        Sat = 7,
    }


    #endregion

}
// </auto-generated>
