
// -----------------------------------------------------------------------------------------
// Failed to read database schema in LoadTables() - The CommandText property has not been properly initialized.
/*   at MySql.Data.MySqlClient.Interceptors.ExceptionInterceptor.Throw(Exception exception)
   at MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   at MySql.Data.MySqlClient.MySqlCommand.<ExecuteReaderAsync>d__111.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.VisualStudio.TextTemplatingA301A6A4D31E8828011B65ED353D0E4E5077174B24ACE8E8BDBD6466B9D9FE36201FDDAD6F695713020CE39F7FBA625B98C2C5EC2AA8002A5780C5BACC1465B4.GeneratedTextTransformation.DatabaseReader.ReadTables(Boolean includeSynonyms) in C:\S\Source (open source)\EntityFramework-Reverse-POCO-Code-First-Generator\Tester.Integration.EFCore6\..\EntityFramework.Reverse.POCO.Generator\EF.Reverse.POCO.v3.ttinclude:line 12717
   at Microsoft.VisualStudio.TextTemplatingA301A6A4D31E8828011B65ED353D0E4E5077174B24ACE8E8BDBD6466B9D9FE36201FDDAD6F695713020CE39F7FBA625B98C2C5EC2AA8002A5780C5BACC1465B4.GeneratedTextTransformation.Generator.LoadTables() in C:\S\Source (open source)\EntityFramework-Reverse-POCO-Code-First-Generator\Tester.Integration.EFCore6\..\EntityFramework.Reverse.POCO.Generator\EF.Reverse.POCO.v3.ttinclude:line 4479*/
// -----------------------------------------------------------------------------------------

// <auto-generated>

namespace MySqlTestDatabaseStandard
{
}
// </auto-generated>
