// <auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace V7EfrpgTest
{
    // SmallDecimalTestAttribute
    public class FkTest_SmallDecimalTestAttributeConfiguration : IEntityTypeConfiguration<FkTest_SmallDecimalTestAttribute>
    {
        public void Configure(EntityTypeBuilder<FkTest_SmallDecimalTestAttribute> builder)
        {
            builder.ToTable("SmallDecimalTestAttribute", "FkTest");
            builder.HasKey(x => x.FkId).HasName("PK_FkTest_SmallDecimalTestAttribute").IsClustered();

            builder.Property(x => x.FkId).HasColumnName(@"FkID").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Description).HasColumnName(@"description").HasColumnType("varchar(20)").IsRequired().IsUnicode(false).HasMaxLength(20);

            // Foreign keys
            builder.HasOne(a => a.SmallDecimalTest).WithOne(b => b.FkTest_SmallDecimalTestAttribute).HasForeignKey<FkTest_SmallDecimalTestAttribute>(c => c.FkId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("KateFK");
        }
    }

}
// </auto-generated>
