-- This database will contain all the horrible edge cases this generator has to cope with

/*CREATE DATABASE [EfrpgTest] ON PRIMARY
       ( NAME = N'EfrpgTest',     FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\EfrpgTest.mdf' , SIZE = 5Mb , FILEGROWTH = 1024KB )
LOG ON ( NAME = N'EfrpgTest_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\EfrpgTest.ldf' , SIZE = 1024KB , FILEGROWTH = 10%);
GO
ALTER DATABASE [EfrpgTest] SET COMPATIBILITY_LEVEL = 100
ALTER DATABASE [EfrpgTest] SET ANSI_NULL_DEFAULT OFF
ALTER DATABASE [EfrpgTest] SET ANSI_NULLS OFF
ALTER DATABASE [EfrpgTest] SET ANSI_PADDING OFF
ALTER DATABASE [EfrpgTest] SET ANSI_WARNINGS OFF
ALTER DATABASE [EfrpgTest] SET ARITHABORT OFF
ALTER DATABASE [EfrpgTest] SET AUTO_CLOSE OFF
ALTER DATABASE [EfrpgTest] SET AUTO_CREATE_STATISTICS ON
ALTER DATABASE [EfrpgTest] SET AUTO_SHRINK OFF
ALTER DATABASE [EfrpgTest] SET AUTO_UPDATE_STATISTICS ON
ALTER DATABASE [EfrpgTest] SET CURSOR_CLOSE_ON_COMMIT OFF
ALTER DATABASE [EfrpgTest] SET CURSOR_DEFAULT  GLOBAL
ALTER DATABASE [EfrpgTest] SET CONCAT_NULL_YIELDS_NULL OFF
ALTER DATABASE [EfrpgTest] SET NUMERIC_ROUNDABORT OFF
ALTER DATABASE [EfrpgTest] SET QUOTED_IDENTIFIER OFF
ALTER DATABASE [EfrpgTest] SET RECURSIVE_TRIGGERS OFF
ALTER DATABASE [EfrpgTest] SET  DISABLE_BROKER
ALTER DATABASE [EfrpgTest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
ALTER DATABASE [EfrpgTest] SET DATE_CORRELATION_OPTIMIZATION OFF
ALTER DATABASE [EfrpgTest] SET PARAMETERIZATION SIMPLE
ALTER DATABASE [EfrpgTest] SET  READ_WRITE
ALTER DATABASE [EfrpgTest] SET RECOVERY SIMPLE
ALTER DATABASE [EfrpgTest] SET  MULTI_USER
ALTER DATABASE [EfrpgTest] SET PAGE_VERIFY CHECKSUM
GO
USE [EfrpgTest]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY')
	ALTER DATABASE [EfrpgTest] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
*/

USE [EfrpgTest]
GO




-- #321 Fix reverse navigation properties for One-To-One relationships
CREATE SCHEMA Stafford
GO
CREATE TABLE Stafford.Boo
(
	id INT IDENTITY(1, 1) NOT NULL,
	[name] NCHAR(10) NOT NULL,
    CONSTRAINT PK_Boo PRIMARY KEY CLUSTERED (id ASC)
);
CREATE TABLE Stafford.Foo
(
	id INT NOT NULL,
    [name] NCHAR(10) NOT NULL,
    CONSTRAINT PK_Foo PRIMARY KEY CLUSTERED (id ASC)
);
GO
ALTER TABLE Stafford.Foo WITH CHECK ADD CONSTRAINT FK_Foo_Boo FOREIGN KEY(id) REFERENCES Stafford.Boo (id);
GO
ALTER TABLE Stafford.Foo CHECK CONSTRAINT FK_Foo_Boo;
GO


