// <auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace V5EfrpgTest
{
    // Versioned
    public class VersionedConfiguration : IEntityTypeConfiguration<Versioned>
    {
        public void Configure(EntityTypeBuilder<Versioned> builder)
        {
            builder.ToTable("Versioned", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_Versioned").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Version).HasColumnName(@"Version").HasColumnType("timestamp(8)").IsRequired().IsFixedLength().HasMaxLength(8).IsRowVersion();
            builder.Property(x => x.Number).HasColumnName(@"Number").HasColumnType("int").IsRequired();
        }
    }

}
// </auto-generated>
