// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Tester.Integration.EfCore3
{
    // DaysOfWeek
    public class EnumTest_DaysOfWeekConfiguration : IEntityTypeConfiguration<EnumTest_DaysOfWeek>
    {
        public void Configure(EntityTypeBuilder<EnumTest_DaysOfWeek> builder)
        {
            builder.ToTable("DaysOfWeek", "EnumTest");
            builder.HasKey(x => x.TypeId).HasName("PK_EnumTest_DaysOfWeek").IsClustered();

            builder.Property(x => x.TypeName).HasColumnName(@"TypeName").HasColumnType("varchar(50)").IsRequired().IsUnicode(false).HasMaxLength(50);
            builder.Property(x => x.TypeId).HasColumnName(@"TypeId").HasColumnType("int").IsRequired().ValueGeneratedNever();
        }
    }

}
// </auto-generated>
