// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Tester.Integration.EfCore3
{
    // TableA
    public class TableAConfiguration : IEntityTypeConfiguration<TableA>
    {
        public void Configure(EntityTypeBuilder<TableA> builder)
        {
            builder.ToTable("TableA", "dbo");
            builder.HasKey(x => x.TableAId).HasName("TableA_pkey").IsClustered();

            builder.Property(x => x.TableAId).HasColumnName(@"TableAId").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.TableADesc).HasColumnName(@"TableADesc").HasColumnType("varchar(20)").IsRequired(false).IsUnicode(false).HasMaxLength(20);
        }
    }

}
// </auto-generated>
