CREATE TABLE [dbo].[A] (
    [AId] INT IDENTITY (1, 1) NOT NULL,
    [C1]  INT NOT NULL,
    [C2]  INT NOT NULL,
    CONSTRAINT [PK_A] PRIMARY KEY CLUSTERED ([AId] ASC),
    CONSTRAINT [FK_A_A] FOREIGN KEY ([C1], [C2]) REFERENCES [dbo].[AAREF] ([C1], [C2])
);

