// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace V7EfrpgTest
{
    // cross_database_synonym
    public class CrossDatabaseSynonym
    {
        public int Id { get; set; } // Id (Primary key)
        public string Forename { get; set; } // Forename (length: 20)
    }

}
// </auto-generated>
