// <auto-generated>

using System;
using System.Collections.Generic;

namespace V7EfrpgTest
{
    public class FFRS_CsvToInt2ReturnModel
    {
        public int? IntValue { get; set; }
    }

}
// </auto-generated>
