// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tester.Integration.EfCore3
{
    // BlahBlargLink
    public class BlahBlargLink
    {
        public int BlahId { get; set; } // BlahID (Primary key)
        public int BlargId { get; set; } // BlargID (Primary key)

        // Foreign keys

        /// <summary>
        /// Parent Blah pointed by [BlahBlargLink].([BlahId]) (FK_BlahBlargLink_Blah)
        /// </summary>
        public Blah Blah { get; set; } // FK_BlahBlargLink_Blah

        /// <summary>
        /// Parent Blarg pointed by [BlahBlargLink].([BlargId]) (FK_BlahBlargLink_Blarg)
        /// </summary>
        public Blarg Blarg { get; set; } // FK_BlahBlargLink_Blarg
    }

}
// </auto-generated>
