// <auto-generated>
// ReSharper disable All

namespace Tester.Integration.EfCore3
{
    public enum ColourEnum
    {
        Red = 1,
        Green = 2,
        Blue = 3,
        AlloyOrange = 4,
        CaféNoir = 5,
        BigDipOruby = 6,
    }

}
// </auto-generated>
