// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Tester.Integration.EfCore3
{
    public class CsvToIntReturnModel
    {
        public int? IntValue { get; set; }
    }

}
// </auto-generated>
