// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tester.Integration.EfCore3
{
    // InflectorData
    public class InflectorData
    {
        public int Id { get; set; } // Id (Primary key)
    }

}
// </auto-generated>
