// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tester.Integration.EfCore3
{
    // table.with.multiple.periods
    public class TableWithMultiplePeriod
    {
        public int Id { get; set; } // id (Primary key)
        public string Description { get; set; } // description (length: 20)
    }

}
// </auto-generated>
