// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tester.Integration.EfCore3
{
    // TableA
    public class TableA
    {
        public int TableAId { get; set; } // TableAId (Primary key)
        public string TableADesc { get; set; } // TableADesc (length: 20)

        // Reverse navigation

        /// <summary>
        /// Child TableBs where [TableB].[TableAId] point to this entity (FK_TableA_CompositeKey_Req)
        /// </summary>
        public ICollection<TableB> TableBs { get; set; } // TableB.FK_TableA_CompositeKey_Req

        public TableA()
        {
            TableBs = new List<TableB>();
        }
    }

}
// </auto-generated>
