// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tester.Integration.EfCore3
{
    // view.with.multiple.periods
    public class ViewWithMultiplePeriod
    {
        public int FkId { get; set; } // FkID
        public string Description { get; set; } // description (length: 20)
    }

}
// </auto-generated>
