// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Tester.Integration.EfCore2
{
    public class DboProcDataFromFfrsReturnModel
    {
        public Guid BatchUID { get; set; }
        public int CVID { get; set; }
        public string CVName { get; set; }
    }

}
// </auto-generated>
