// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Tester.Integration.EfCore2
{
    public class TestReturnStringReturnModel
    {
        public string error { get; set; }
    }

}
// </auto-generated>
