// <auto-generated>

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using Tester.Integration.EFCore8.Single_context_many_files.Configuration;
using Tester.Integration.EFCore8.Single_context_many_files.Contexts;
using Tester.Integration.EFCore8.Single_context_many_files.Interfaces;

namespace Tester.Integration.EFCore8.Single_context_many_files.Entities
{
    // UserFacilityServiceRole
    public class App_UserFacilityServiceRole
    {
        public int UserId { get; set; } // userId (Primary key)
        public int AppId { get; set; } // appId (Primary key)
        public int FsrId { get; set; } // fsrId (Primary key)
    }

}
// </auto-generated>
