// <auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tester.Integration.EFCore8.Single_context_many_files
{
    // BatchTest
    public class BatchTest
    {
        public string Code { get; set; } = null!; // code (Primary key) (length: 8)
    }

}
// </auto-generated>
