// <auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tester.Integration.EFCore8.Single_context_many_files
{
    // BITFIDDLERALLCAPS
    public class Bitfiddlerallcap
    {
        public int Id { get; set; } // Id (Primary key)
    }

}
// </auto-generated>
