// <auto-generated>

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using Tester.Integration.EFCore8.Single_context_many_files.Configuration;
using Tester.Integration.EFCore8.Single_context_many_files.Contexts;
using Tester.Integration.EFCore8.Single_context_many_files.Interfaces;

namespace Tester.Integration.EFCore8.Single_context_many_files.Entities
{
    public class C182Test1ReturnModel
    {
        public int? Id { get; set; }
        public string Description { get; set; }
    }

}
// </auto-generated>
