// <auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tester.Integration.EFCore8.Single_context_many_files
{
    // CMS_Tag
    public class CmsTag
    {
        public int TagId { get; set; } // TagId (Primary key)
        public string TagName { get; set; } // TagName (length: 100)

        // Reverse navigation

        /// <summary>
        /// Child CmsFileTags where [CMS_FileTag].[TagId] point to this entity (FK_CMS_FileTag_CMS_Tag)
        /// </summary>
        public virtual ICollection<CmsFileTag> CmsFileTags { get; set; } // CMS_FileTag.FK_CMS_FileTag_CMS_Tag

        public CmsTag()
        {
            CmsFileTags = new List<CmsFileTag>();
        }
    }

}
// </auto-generated>
