// <auto-generated>

using System;
using System.Collections.Generic;

namespace Tester.Integration.EFCore8.Single_context_many_files
{
    public class ColourPivotReturnModel
    {
        public int? Blue { get; set; }
        public int? Green { get; set; }
        public int? Red { get; set; }
    }

}
// </auto-generated>
