// <auto-generated>

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

namespace Tester.Integration.EFCore8.Single_context_many_files
{
    // ComplexView
    public class ComplexView
    {
        public string LicenseType { get; set; } // LicenseType (length: 128)
        public int? Count { get; set; } // Count
    }

}
// </auto-generated>
