// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tester.Integration.EFCore8.Single_context_many_files
{
    // CV
    public class FFRS_Cv
    {
        public Guid BatchUid { get; set; } // BatchUID (Primary key)
        public int Cvid { get; set; } // CVID (Primary key)
        public string CvName { get; set; } // CVName (length: 200)
    }

}
// </auto-generated>
