// <auto-generated>

using System;
using System.Collections.Generic;

namespace Tester.Integration.EFCore8.Single_context_many_files
{
    public class GetSmallDecimalTestReturnModel
    {
        public int id { get; set; }
        public decimal? KoeffVed { get; set; }
    }

}
// </auto-generated>
