// <auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using Tester.Integration.EFCore8.Single_context_many_files.Configuration;
using Tester.Integration.EFCore8.Single_context_many_files.Contexts;
using Tester.Integration.EFCore8.Single_context_many_files.Interfaces;

namespace Tester.Integration.EFCore8.Single_context_many_files.Entities
{
    // Period.Table
    public class PeriodTable
    {
        public int Id { get; set; } // id (Primary key)
        public int? JoeBloggs { get; set; } // joe.bloggs
    }

}
// </auto-generated>
