// <auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using Tester.Integration.EFCore8.Single_context_many_files.Configuration;
using Tester.Integration.EFCore8.Single_context_many_files.Contexts;
using Tester.Integration.EFCore8.Single_context_many_files.Interfaces;

namespace Tester.Integration.EFCore8.Single_context_many_files.Entities
{
    // SorterScannerGroup
    public class SorterScannerGroup
    {
        public string SorterName { get; set; } = null!; // SorterName (Primary key) (length: 20)

        // Foreign keys

        /// <summary>
        /// Parent Sorter pointed by [SorterScannerGroup].([SorterName]) (FK_SorterScannerGroup_Sorters)
        /// </summary>
        public virtual Sorters Sorter { get; set; } = null!; // FK_SorterScannerGroup_Sorters
    }

}
// </auto-generated>
