// <auto-generated>
#nullable enable

using System;
using System.Collections.Generic;

namespace Tester.Integration.EFCore8.Single_context_many_files
{
    public class SpatialTypesWithParamsReturnModel
    {
        public int Dollar { get; set; }
        public NetTopologySuite.Geometries.Point GeographyType { get; set; } = null!;
        public NetTopologySuite.Geometries.Geometry GeometryType { get; set; } = null!;
    }

}
// </auto-generated>
