// <auto-generated>

using System;
using System.Collections.Generic;

namespace Tester.Integration.EFCore8.Single_context_many_files
{
    public class StpTestUnderscoreTestReturnModel
    {
        public int code_object_no { get; set; }
        public int? application_no { get; set; }
    }

}
// </auto-generated>
