// <auto-generated>

using System;
using System.Collections.Generic;

namespace Tester.Integration.EFCore8.Single_context_many_files
{
    public class StpTestReturnModel
    {
        public int codeObjectNo { get; set; }
        public int? applicationNo { get; set; }
        public int type { get; set; }
        public string eName { get; set; }
        public string aName { get; set; }
        public string description { get; set; }
        public string codeName { get; set; }
        public string note { get; set; }
        public bool isObject { get; set; }
        public byte[] versionNumber { get; set; }
    }

}
// </auto-generated>
