// <auto-generated>

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using Tester.Integration.EFCore8.Single_context_many_files.Configuration;
using Tester.Integration.EFCore8.Single_context_many_files.Contexts;
using Tester.Integration.EFCore8.Single_context_many_files.Interfaces;

namespace Tester.Integration.EFCore8.Single_context_many_files.Entities
{
    // TableA
    public class TableA
    {
        public int TableAId { get; set; } // TableAId (Primary key)
        public string TableADesc { get; set; } // TableADesc (length: 20)

        // Reverse navigation

        /// <summary>
        /// Child TableBs where [TableB].[TableAId] point to this entity (FK_TableA_CompositeKey_Req)
        /// </summary>
        public virtual ICollection<TableB> TableBs { get; set; } // TableB.FK_TableA_CompositeKey_Req

        public TableA()
        {
            TableBs = new List<TableB>();
        }
    }

}
// </auto-generated>
