// <auto-generated>

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

namespace Tester.Integration.EFCore8.Single_context_many_files
{
    // table with duplicate column names
    public class TableWithDuplicateColumnName
    {
        public int Id { get; set; } // id (Primary key)
        public int UserId1 { get; set; } // user_id
        public int UserId2 { get; set; } // UserId
        public int UserId3 { get; set; } // User Id
        public int UserId4 { get; set; } // User  Id
        public int UserId { get; set; } // user__id
    }

}
// </auto-generated>
