// <auto-generated>

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using Tester.Integration.EFCore8.Single_context_many_files.Configuration;
using Tester.Integration.EFCore8.Single_context_many_files.Contexts;
using Tester.Integration.EFCore8.Single_context_many_files.Interfaces;

namespace Tester.Integration.EFCore8.Single_context_many_files.Entities
{
    // TemporalDepartment
    public class TemporalDepartment
    {
        public int DeptId { get; set; } // DeptID (Primary key)
        public string DeptName { get; set; } // DeptName (length: 50)
        public int? ManagerId { get; set; } // ManagerID
        public int? ParentDeptId { get; set; } // ParentDeptID
        public DateTime SysStartTime { get; set; } // SysStartTime
        public DateTime SysEndTime { get; set; } // SysEndTime
    }

}
// </auto-generated>
