// <auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tester.Integration.EFCore8.Single_context_many_files
{
    // view.with.multiple.periods
    public class ViewWithMultiplePeriod
    {
        public int FkId { get; set; } // FkID
        public string Description { get; set; } // description (length: 20)
    }

}
// </auto-generated>
