// <auto-generated>

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using Tester.Integration.EFCore8.Single_context_many_files.Configuration;
using Tester.Integration.EFCore8.Single_context_many_files.Contexts;
using Tester.Integration.EFCore8.Single_context_many_files.Interfaces;

namespace Tester.Integration.EFCore8.Single_context_many_files.Entities
{
    // view.with.multiple.periods
    public class ViewWithMultiplePeriod
    {
        public int FkId { get; set; } // FkID
        public string Description { get; set; } // description (length: 20)
    }

}
// </auto-generated>
