// <auto-generated>

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using Tester.Integration.EFCore8.Single_context_many_files.Configuration;
using Tester.Integration.EFCore8.Single_context_many_files.Contexts;
using Tester.Integration.EFCore8.Single_context_many_files.Interfaces;

namespace Tester.Integration.EFCore8.Single_context_many_files.Entities
{
    // Бренды товара
    public class Брендытовара
    {
        public int Кодбренда { get; set; } // Код бренда (Primary key)
        public string Наименованиебренда { get; set; } // Наименование бренда (length: 50)
        public byte[] Логотипбренда { get; set; } // Логотип_бренда (length: 2147483647)
        public byte[] Логотипбрендавертикальный { get; set; } // Логотип_бренда_вертикальный (length: 2147483647)
    }

}
// </auto-generated>
