namespace Generator.Tests.Unit
{
    using Efrpg;
    using Efrpg.FileManagement;
    using Efrpg.Filtering;
    using Efrpg.Generators;
    using Efrpg.Templates;
    using Generator.Tests.Common;
    using NUnit.Framework;
    using System;

    // Issue #883 - the generated EF Core 8+ interface, DbContext, DbContext factory, fake context
    // and fake DbSet carry hard-coded nullable reference annotations (IConfiguration?,
    // DbContextOptions<>?, Find/FindAsync, ToString). For files marked // <auto-generated> the
    // compiler treats the nullable annotation context as disabled, so without an explicit directive
    // those '?' raise CS8669. When the file header doesn't already carry '#nullable enable'
    // (NeedsNullForgiving() == false) each block is bracketed with
    // '#nullable enable annotations' ... '#nullable restore'. Annotation-only context is used so the
    // '?' is legal without forcing CS8618 on the DbContext's uninitialised DbSet<T> properties.
    [TestFixture, NonParallelizable]
    [Category(Constants.CI)]
    public class NullableContextTests
    {
        [TearDown]
        public void TearDown()
        {
            // Settings is static; restore the values this fixture changes so other fixtures are unaffected.
            Settings.AllowNullStrings                    = false;
            Settings.NullableReverseNavigationProperties = false;
            Settings.OnConfiguration                     = OnConfiguration.ConnectionString;
            Settings.UseDataAnnotations                  = false;
        }

        // Builds a CodeGenerator for a single-table EF Core context, mirroring ViewTests.
        // allowNullStrings drives NeedsNullForgiving(): false => header has no '#nullable enable',
        // so the per-block bracket is required.
        private static CodeGenerator BuildSingleTableEfCoreGenerator(TemplateType templateType, bool allowNullStrings)
        {
            Settings.TemplateType                        = templateType;
            Settings.GeneratorType                       = GeneratorType.EfCore;
            Settings.UseDataAnnotations                  = false;
            Settings.AddIDbContextFactory                = true;                          // factory must be generated
            Settings.ElementsToGenerate                  = Elements.Context | Elements.Poco | Elements.PocoConfiguration;
            Settings.OnConfiguration                     = OnConfiguration.Configuration;  // makes the DbContext emit IConfiguration?
            Settings.DbContextName                       = "TestDbContext";
            Settings.AllowNullStrings                    = allowNullStrings;               // drives NeedsNullForgiving()
            Settings.NullableReverseNavigationProperties = false;

            FilterSettings.Reset();
            FilterSettings.AddDefaults();
            FilterSettings.CheckSettings();

            var fileManagement = new FileManagementService(new GeneratedTextTransformation());
            var generator      = new GeneratorEfCore(fileManagement, typeof(NullFileManager));

            var table = new Table(null, new Schema("dbo"), "Customer", false) { NameHumanCase = "Customer" };
            table.Columns.Add(new Column
            {
                DbName          = "Id",
                NameHumanCase   = "Id",
                IsPrimaryKey    = true,
                PropertyType    = "int",
                SqlPropertyType = "int",   // GenerateContext inspects SqlPropertyType (hierarchyid check); must be non-null
                Config          = "builder.Property(x => x.Id).IsRequired();",
                ParentTable     = table
            });
            table.SetPrimaryKeys();

            var filter = new SingleContextFilter();
            filter.Tables.Add(table);

            return new CodeGenerator(generator, filter);
        }

        // The factory always declares 'DbContextOptions<...>? Options', so it always needs the bracket.
        [Test]
        [TestCase(TemplateType.EfCore8)]
        [TestCase(TemplateType.EfCore9)]
        [TestCase(TemplateType.EfCore10)]
        public void GenerateFactory_EfCore8Plus_WithoutNullForgiving_BracketsTheNullableAnnotation(TemplateType templateType)
        {
            // Arrange
            var codeGen = BuildSingleTableEfCoreGenerator(templateType, allowNullStrings: false);

            // Act
            var output = codeGen.GenerateFactory();

            // Assert
            Assert.IsNotNull(output, "GenerateFactory returned null");
            CollectionAssert.Contains(output.Code, "#nullable enable annotations");
            CollectionAssert.Contains(output.Code, "#nullable restore");
            // Annotation-only context, NOT a full '#nullable enable' (which would force CS8618 on DbSet<T>).
            CollectionAssert.DoesNotContain(output.Code, "#nullable enable");

            // The 'DbContextOptions<>? Options' annotation must sit between the enable and restore directives.
            var code            = string.Join(Environment.NewLine, output.Code);
            var enableIndex     = code.IndexOf("#nullable enable annotations", StringComparison.Ordinal);
            var annotationIndex = code.IndexOf("DbContextOptions",             StringComparison.Ordinal);
            var restoreIndex    = code.IndexOf("#nullable restore",            StringComparison.Ordinal);
            Assert.That(annotationIndex, Is.GreaterThan(enableIndex),     "DbContextOptions<>? must be inside the #nullable region");
            Assert.That(restoreIndex,    Is.GreaterThan(annotationIndex), "'#nullable restore' must follow the annotation");
        }

        // The DbContext emits 'IConfiguration? _configuration' when OnConfiguration == Configuration.
        [Test]
        [TestCase(TemplateType.EfCore8)]
        [TestCase(TemplateType.EfCore9)]
        public void GenerateContext_EfCore8Plus_WithoutNullForgiving_BracketsTheNullableAnnotation(TemplateType templateType)
        {
            // Arrange
            var codeGen = BuildSingleTableEfCoreGenerator(templateType, allowNullStrings: false);

            // Act
            var output = codeGen.GenerateContext();

            // Assert
            Assert.IsNotNull(output, "GenerateContext returned null");
            CollectionAssert.Contains(output.Code, "#nullable enable annotations");
            CollectionAssert.Contains(output.Code, "#nullable restore");
            CollectionAssert.DoesNotContain(output.Code, "#nullable enable");

            var code             = string.Join(Environment.NewLine, output.Code);
            var enableIndex      = code.IndexOf("#nullable enable annotations", StringComparison.Ordinal);
            var annotationIndex  = code.IndexOf("IConfiguration? _configuration", StringComparison.Ordinal);
            var restoreIndex     = code.IndexOf("#nullable restore",            StringComparison.Ordinal);
            Assert.That(annotationIndex, Is.GreaterThan(enableIndex),     "IConfiguration? must be inside the #nullable region");
            Assert.That(restoreIndex,    Is.GreaterThan(annotationIndex), "'#nullable restore' must follow the annotation");
        }

        // When NeedsNullForgiving() is true the file header already carries a file-level '#nullable enable',
        // so the per-block bracket must NOT be emitted (it would be redundant).
        [Test]
        public void GenerateFactory_WhenNullForgiving_DoesNotAddPerBlockBracket()
        {
            // Arrange - AllowNullStrings => NeedsNullForgiving() == true
            var codeGen = BuildSingleTableEfCoreGenerator(TemplateType.EfCore8, allowNullStrings: true);

            // Act
            var output = codeGen.GenerateFactory();

            // Assert
            Assert.IsNotNull(output, "GenerateFactory returned null");
            CollectionAssert.DoesNotContain(output.Code, "#nullable enable annotations");
        }
    }
}
