// <auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Tester.Integration.EFCore8.Single_context_many_files
{
    // NullableReverseNavigationA
    public class NullableReverseNavigationAConfiguration : IEntityTypeConfiguration<NullableReverseNavigationA>
    {
        public void Configure(EntityTypeBuilder<NullableReverseNavigationA> builder)
        {
            builder.ToTable("NullableReverseNavigationA", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_NullableReverseNavigationA").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Data).HasColumnName(@"Data").HasColumnType("nvarchar(100)").IsRequired(false).HasMaxLength(100);
        }
    }

}
// </auto-generated>
