// <auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System.Text.Json.Serialization;

namespace Tester.Integration.EFCore8.Single_context_many_files
{
    // Issue
    public class OneEightSix_IssueConfiguration : IEntityTypeConfiguration<OneEightSix_Issue>
    {
        public void Configure(EntityTypeBuilder<OneEightSix_Issue> builder)
        {
            builder.ToTable("Issue", "OneEightSix");
            builder.HasKey(x => x.Id).HasName("PK_Issue").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Title).HasColumnName(@"Title").HasColumnType("nvarchar(100)").IsRequired().HasMaxLength(100);
            builder.Property(x => x.Content).HasColumnName(@"Content").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.ConsentDocumentId).HasColumnName(@"ConsentDocumentId").HasColumnType("int").IsRequired(false);

            // Foreign keys
            builder.HasOne(a => a.OneEightSix_UploadedFile).WithMany(b => b.OneEightSix_Issues).HasForeignKey(c => c.ConsentDocumentId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_Issue_UploadedFileConsentDocument");
        }
    }

}
// </auto-generated>
