// <auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Tester.Integration.EFCore8.Single_context_many_files
{
    // table.with.multiple.periods
    public class TableWithMultiplePeriodConfiguration : IEntityTypeConfiguration<TableWithMultiplePeriod>
    {
        public void Configure(EntityTypeBuilder<TableWithMultiplePeriod> builder)
        {
            builder.ToTable("table.with.multiple.periods", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_table_with_multiple_periods").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"id").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Description).HasColumnName(@"description").HasColumnType("varchar(20)").IsRequired().IsUnicode(false).HasMaxLength(20);
        }
    }

}
// </auto-generated>
