// <auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System.Text.Json.Serialization;
using Tester.Integration.EFCore8.Single_context_many_files.Contexts;
using Tester.Integration.EFCore8.Single_context_many_files.Entities;
using Tester.Integration.EFCore8.Single_context_many_files.Interfaces;

namespace Tester.Integration.EFCore8.Single_context_many_files.Configuration
{
    // tblOrderErrors
    public class TblOrderErrorConfiguration : IEntityTypeConfiguration<TblOrderError>
    {
        public void Configure(EntityTypeBuilder<TblOrderError> builder)
        {
            builder.ToTable("tblOrderErrors", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_tblOrderErrors").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Error).HasColumnName(@"error").HasColumnType("varchar(50)").IsRequired(false).IsUnicode(false).HasMaxLength(50);
        }
    }

}
// </auto-generated>
