// <auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System.Text.Json.Serialization;
using Tester.Integration.EFCore8.Single_context_many_files.Contexts;
using Tester.Integration.EFCore8.Single_context_many_files.Entities;
using Tester.Integration.EFCore8.Single_context_many_files.Interfaces;

namespace Tester.Integration.EFCore8.Single_context_many_files.Configuration
{
    // TimestampNotNull
    public class TimestampNotNullConfiguration : IEntityTypeConfiguration<TimestampNotNull>
    {
        public void Configure(EntityTypeBuilder<TimestampNotNull> builder)
        {
            builder.ToTable("TimestampNotNull", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_TimestampNotNull").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Version).HasColumnName(@"Version").HasColumnType("timestamp").IsRequired().IsFixedLength().IsRowVersion().IsConcurrencyToken();
            builder.Property(x => x.Number).HasColumnName(@"Number").HasColumnType("int").IsRequired();
        }
    }

}
// </auto-generated>
