// <auto-generated>

using System;
using System.Collections.Generic;

namespace V6EfrpgTest
{
    public class CheckIfApplicationIsCompleteReturnModel
    {
        public string Key { get; set; }
        public string Value { get; set; }
    }

}
// </auto-generated>
