// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace V6EfrpgTest
{
    // DefaultCheckForNull
    public class DefaultCheckForNull
    {
        public int Id { get; set; } // Id (Primary key)
        public string DescUppercase { get; set; } // DescUppercase (length: 5)
        public string DescLowercase { get; set; } // DescLowercase (length: 5)
        public string DescMixedCase { get; set; } // DescMixedCase (length: 5)
        public string DescBrackets { get; set; } // DescBrackets (length: 5)
        public string X1 { get; set; } // X1 (length: 255)
    }

}
// </auto-generated>
