// <auto-generated>

using System;
using System.Collections.Generic;

namespace V6EfrpgTest
{
    public class FkTest_HelloReturnModel
    {
        public int? @static { get; set; }
        public int? @readonly { get; set; }
    }

}
// </auto-generated>
