// <auto-generated>

using System;
using System.Collections.Generic;

namespace V6EfrpgTest
{
    public class GetSmallDecimalTestReturnModel
    {
        public int id { get; set; }
        public decimal? KoeffVed { get; set; }
    }

}
// </auto-generated>
