// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace V6EfrpgTest
{
    // InflectorData
    public class InflectorData
    {
        public int Id { get; set; } // Id (Primary key)
    }

}
// </auto-generated>
