// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace V6EfrpgTest
{
    // PeriodTestTable
    public class PeriodTestTable
    {
        public int Id { get; set; } // id (Primary key)
        public int? Joe46Bloggs { get; set; } // joe.bloggs
    }

}
// </auto-generated>
