// <auto-generated>

using System;
using System.Collections.Generic;

namespace V6EfrpgTest
{
    public class StoredProcWithDefaultsReturnModel
    {
        public int? SingleValue { get; set; }
    }

}
// </auto-generated>
