// <auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Tester.Integration.EFCore6.Single_context_many_files
{
    // Sorters
    public class SortersConfiguration : IEntityTypeConfiguration<Sorters>
    {
        public void Configure(EntityTypeBuilder<Sorters> builder)
        {
            builder.ToTable("Sorters", "dbo");
            builder.HasKey(x => x.SorterName).HasName("PK_Sorter").IsClustered();

            builder.Property(x => x.SorterName).HasColumnName(@"SorterName").HasColumnType("varchar(20)").IsRequired().IsUnicode(false).HasMaxLength(20).ValueGeneratedNever();
        }
    }

}
// </auto-generated>
