// <auto-generated>

using Generator.Tests.Common;
using Microsoft.EntityFrameworkCore.Design;

namespace Tester.Integration.EFCore6.Multi_context_many_filesCherry
{
    public class CherryDbContextFactory : IDesignTimeDbContextFactory<CherryDbContext>
    {
        public CherryDbContext CreateDbContext(string[] args)
        {
            return new CherryDbContext();
        }
    }
}
// </auto-generated>
