// <auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace V6EfrpgTest
{
    // CV
    public class FFRS_CvConfiguration : IEntityTypeConfiguration<FFRS_Cv>
    {
        public void Configure(EntityTypeBuilder<FFRS_Cv> builder)
        {
            builder.ToTable("CV", "FFRS");
            builder.HasKey(x => new { x.BatchUid, x.Cvid });

            builder.Property(x => x.BatchUid).HasColumnName(@"BatchUID").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Cvid).HasColumnName(@"CVID").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.CvName).HasColumnName(@"CVName").HasColumnType("nvarchar(200)").IsRequired(false).HasMaxLength(200);
        }
    }

}
// </auto-generated>
