// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tester.Integration.EfCore2
{
    // BlahBlahLink_readonly
    public class BlahBlahLinkReadonly
    {
        public int BlahId { get; set; } // BlahID (Primary key)
        public int BlahId2 { get; set; } // BlahID2 (Primary key)
        public byte[] RowVersion { get; set; } // RowVersion (length: 8)
        public int Id { get; set; } // id
        public int? Id2 { get; private set; } // id2

        // Foreign keys

        /// <summary>
        /// Parent Blah pointed by [BlahBlahLink_readonly].([BlahId]) (FK_BlahBlahLink_Blah_ro)
        /// </summary>
        public virtual Blah Blah_BlahId { get; set; } // FK_BlahBlahLink_Blah_ro

        /// <summary>
        /// Parent Blah pointed by [BlahBlahLink_readonly].([BlahId2]) (FK_BlahBlahLink_Blah_ro2)
        /// </summary>
        public virtual Blah Blah_BlahId2 { get; set; } // FK_BlahBlahLink_Blah_ro2
    }

}
// </auto-generated>
