// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Tester.Integration.EfCore2
{
    public class C182Test1ReturnModel
    {
        public int? Id { get; set; }
        public string Description { get; set; }
    }

}
// </auto-generated>
