// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tester.Integration.EfCore2
{
    // PeriodTestTable
    public class PeriodTestTable
    {
        public int Id { get; set; } // id (Primary key)
        public int? Joe46Bloggs { get; set; } // joe.bloggs
    }

}
// </auto-generated>
