// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Tester.Integration.EfCore2
{
    public class StpTestUnderscoreTestReturnModel
    {
        public int code_object_no { get; set; }
        public int? application_no { get; set; }
    }

}
// </auto-generated>
