// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tester.Integration.EfCore2
{
    // ThisIsMemoryOptimised
    public class ThisIsMemoryOptimised
    {
        public int Id { get; set; } // Id (Primary key)
        public string Description { get; set; } // Description (length: 20)
    }

}
// </auto-generated>
