// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.co.uk/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Registered to: Simon Hughes
// Company      : Reverse POCO
// Licence Type : Commercial
// Licences     : 1
// Valid until  : 15 DEC 2022
//
// The following connection settings were used to generate this file:
//     Connection String Name: "FredDbContext"
//     Connection String:      "Data Source=(local);Initial Catalog=Fred;Integrated Security=True"
//
// Database Edition       : Developer Edition (64-bit)
// Database Engine Edition: Enterprise
// Database Version       : 14.0.2037.2
//
// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace V3Fred
{
    // CMS_FileTag
    public class CmsFileTag
    {
        public int FileId { get; set; } // FileId (Primary key)
        public int TagId { get; set; } // TagId (Primary key)

        // Foreign keys

        /// <summary>
        /// Parent CmsFile pointed by [CMS_FileTag].([FileId]) (FK_CMS_FileTag_CMS_File)
        /// </summary>
        public virtual CmsFile CmsFile { get; set; } // FK_CMS_FileTag_CMS_File

        /// <summary>
        /// Parent CmsTag pointed by [CMS_FileTag].([TagId]) (FK_CMS_FileTag_CMS_Tag)
        /// </summary>
        public virtual CmsTag CmsTag { get; set; } // FK_CMS_FileTag_CMS_Tag
    }

}
// </auto-generated>
