// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Tester.Integration.EfCore3
{
    public class Kate_HelloReturnModel
    {
        public int? @static { get; set; }
        public int? @readonly { get; set; }
    }

}
// </auto-generated>
