// <auto-generated>

using Generator.Tests.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;

namespace Tester.Integration.EFCore8.Multi_context_many_filesBananaDbContext
{
    public class BananaDbContextFactory : IDesignTimeDbContextFactory<BananaDbContext>
    {
        private readonly DbContextOptions<BananaDbContext> Options;

        public BananaDbContextFactory()
        {
        }

        public BananaDbContextFactory(DbContextOptions<BananaDbContext> options)
        {
            Options = options;
        }

        public BananaDbContext CreateDbContext(string[] args)
        {
            return new BananaDbContext();
        }

        public BananaDbContext CreateDbContext()
        {
            return new BananaDbContext(Options);
        }

        public BananaDbContext CreateDbContext(DbContextOptions<BananaDbContext> options)
        {
            return options == null
                ? new BananaDbContext()
                : new BananaDbContext(options);
        }
    }
}
// </auto-generated>
