// <auto-generated>

using Generator.Tests.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using System.Text.Json.Serialization;

namespace Tester.Integration.EFCore8.Multi_context_many_filesCherry
{
    public class CherryDbContextFactory : IDesignTimeDbContextFactory<CherryDbContext>
    {
        private readonly DbContextOptions<CherryDbContext> Options;

        public CherryDbContextFactory()
        {
        }

        public CherryDbContextFactory(DbContextOptions<CherryDbContext> options)
        {
            Options = options;
        }

        public CherryDbContext CreateDbContext(string[] args)
        {
            return new CherryDbContext();
        }

        public CherryDbContext CreateDbContext()
        {
            return new CherryDbContext(Options);
        }

        public CherryDbContext CreateDbContext(DbContextOptions<CherryDbContext> options)
        {
            return options == null
                ? new CherryDbContext()
                : new CherryDbContext(options);
        }
    }
}
// </auto-generated>
