// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace V6Fred
{
    // RebelGalaxyBroadsides
    public class RebelGalaxyBroadside
    {
        public string WeaponName { get; set; } // WeaponName (length: 30)
        public int Damage { get; set; } // Damage (Primary key)
        public int Cost { get; set; } // Cost (Primary key)
    }

}
// </auto-generated>
