// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace V6Fred
{
    // StockPrediction
    public class StockPrediction
    {
        public int Id { get; set; } // id (Primary key)
        public string Name { get; set; } // name (length: 50)
        public DateTime Date { get; set; } // date
        public decimal Open { get; set; } // open
        public decimal High { get; set; } // high
        public decimal Low { get; set; } // low
        public decimal Close { get; set; } // close
        public decimal AdjClose { get; set; } // adj_close
        public int Volume { get; set; } // volume
        public bool? Buy { get; set; } // buy
    }

}
// </auto-generated>
