// <auto-generated>

using System;
using System.Collections.Generic;

namespace V6Fred
{
    public class StpNullableParamsTestReturnModel
    {
        public int codeObjectNo { get; set; }
        public int? applicationNo { get; set; }
    }

}
// </auto-generated>
