using System.Text;

namespace Efrpg.Generators
{
    public class FileHeaderFooter
    {
        public readonly string Header;
        public readonly string Namespace;
        public readonly string Footer;

        public FileHeaderFooter(string subNamespace)
        {
            var header = new StringBuilder(1024);
            header.AppendLine("// <auto-generated>");
            header.AppendLine("// ReSharper disable CheckNamespace");
            header.AppendLine("// ReSharper disable ConvertPropertyToExpressionBody");
            header.AppendLine("// ReSharper disable DoNotCallOverridableMethodsInConstructor");
            header.AppendLine("// ReSharper disable EmptyNamespace");
            header.AppendLine("// ReSharper disable InconsistentNaming");
            header.AppendLine("// ReSharper disable NotAccessedVariable");
            header.AppendLine("// ReSharper disable PartialMethodWithSinglePart");
            header.AppendLine("// ReSharper disable PartialTypeWithSinglePart");
            header.AppendLine("// ReSharper disable RedundantCast");
            header.AppendLine("// ReSharper disable RedundantNameQualifier");
            header.AppendLine("// ReSharper disable RedundantOverridenMember");
            header.AppendLine("// ReSharper disable UseNameofExpression");
            header.AppendLine("// ReSharper disable UsePatternMatching");
            if(Settings.UsePragma)
                header.AppendLine("#pragma warning disable 1591    //  Ignore \"Missing XML Comment\" warning");
            Header = header.ToString();

            header = new StringBuilder(500);
            if (Settings.UseNamespace)
            {
                header.AppendLine("namespace " + Settings.Namespace + subNamespace);
                header.Append("{");
            }

            Namespace = header.ToString();

            var footer = new StringBuilder(30);
            if (Settings.UseNamespace)
                footer.AppendLine("}");
            footer.AppendLine("// </auto-generated>");
            Footer = footer.ToString();

        }
    }
}