
// <auto-generated>

using Microsoft.EntityFrameworkCore.Design;

namespace Tester.Integration.EfCore3.Multi_context_many_filesBananaDbContext
{
    public class BananaDbContextFactory : IDesignTimeDbContextFactory<BananaDbContext>
    {
        public BananaDbContext CreateDbContext(string[] args)
        {
            return new BananaDbContext();
        }
    }
}
// </auto-generated>
