// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace V5Fred
{
    // EnumsWithStringAsValue
    public class EnumsWithStringAsValue
    {
        public string EnumName { get; set; } // enum_name (Primary key) (length: 50)
        public string Value { get; set; } // value (Primary key) (length: 10)
    }

}
// </auto-generated>
