// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace V5Fred
{
    // KatieView
    public class KatieView
    {
        public int KateId { get; set; } // KateID
        public string Description { get; set; } // description (length: 20)
    }

}
// </auto-generated>
