// <auto-generated>

using System;
using System.Collections.Generic;

namespace V5Fred
{
    public class SpatialTypesWithParamsReturnModel
    {
        public int Dollar { get; set; }
        public NetTopologySuite.Geometries.Point GeographyType { get; set; }
        public NetTopologySuite.Geometries.Geometry GeometryType { get; set; }
    }

}
// </auto-generated>
