// <auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace V6Fred
{
    // RebelGalaxyBroadsides
    public class RebelGalaxyBroadsideConfiguration : IEntityTypeConfiguration<RebelGalaxyBroadside>
    {
        public void Configure(EntityTypeBuilder<RebelGalaxyBroadside> builder)
        {
            builder.ToTable("RebelGalaxyBroadsides", "dbo");
            builder.HasKey(x => new { x.Damage, x.Cost });

            builder.Property(x => x.WeaponName).HasColumnName(@"WeaponName").HasColumnType("varchar(30)").IsRequired(false).IsUnicode(false).HasMaxLength(30);
            builder.Property(x => x.Damage).HasColumnName(@"Damage").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Cost).HasColumnName(@"Cost").HasColumnType("int").IsRequired().ValueGeneratedNever();
        }
    }

}
// </auto-generated>
