// <auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace V5EfrpgTest
{
    // cross_database_synonym
    public class CrossDatabaseSynonym
    {
        public int Id { get; set; } // Id (Primary key)
        public string Description { get; set; } // description (length: 100)
        public string PhoneNumber { get; set; } // phone_number (length: 20)
    }

}
// </auto-generated>
