// <auto-generated>

using System;
using System.Collections.Generic;

namespace V5EfrpgTest
{
    public class CsvToIntReturnModel
    {
        public int? IntValue { get; set; }
    }

}
// </auto-generated>
