// <auto-generated>

using System;
using System.Collections.Generic;

namespace V5EfrpgTest
{
    public class StpNoParamsTestReturnModel
    {
        public int codeObjectNo { get; set; }
        public int? applicationNo { get; set; }
    }

}
// </auto-generated>
